version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "80:80"
    environment:
      - DOMAIN=localhost
      - DRAWING_IP=drawing
      - DRAWING_PORT=4000
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - drawing

  drawing:
    build:
      context: ./drawing
      dockerfile: dockerfile
    ports:
      - "4000:4000"
    environment:
      - REDIS_HOST=10.0.1.40
      - REDIS_PORT=6379
      - MIX_ENV=prod
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
