FROM golang:1.25 AS build

WORKDIR /usr/src/app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o app main.go


FROM alpine:3.14

WORKDIR /usr/src/app

COPY --from=build  /usr/src/app/app ./app
CMD [ "./app" ]

